### ISSUE TITLE
issue with time_bnds in netcdf file

### ISSUE THREAD

**Issue by Peter-Gibson** [oloapinivad/MiLES#2]
I noticed that an error is produced in the function 'ncdf.opener.time' from  **basis_functions.R** when running on netcdf files that contain variable **time_bnds**

on line:
`for (axis in naxis) {print(axis); assign(axis,ncvar_get(a,axis))}`

I fixed the error by using nco to strip the time_bnds from my netcdf file first:
` ncks -C -O -x -v time_bnds iflile ofile`

However, since time_bnds are common in many files ..... it might be better to modify the naxis loop in R

**Comment by oloapinivad** [comment]
Thanks Peter for reporting this.
I will try to fix it as soon as I can.
Just to double check, are you running the script on a preprocessed file by
CDO?
I am asking this because I have never experienced such issue...

Best,
Paolo

2018-01-26 23:29 GMT+00:00 Peter Gibson <notifications@github.com>:

**Comment by Peter-Gibson** [comment]
Hi Paolo,

Thanks for the reply.

Yes I had 'z500_prepare.sh' first on my data. And before that I had used cdo to pre-process the data (e.g. calculating daymean from 6hrly data). At some point in the pre-processing it seems time_bnds was being added as a variable:

dimensions:
	longitude = 480 ;
	latitude = 241 ;
	time = UNLIMITED ; // (13149 currently)
	bnds = 2 ;
variables:
	float longitude(longitude) ;
		longitude:standard_name = "longitude" ;
		longitude:long_name = "longitude" ;
		longitude:units = "degrees_east" ;
		longitude:axis = "X" ;
	float latitude(latitude) ;
		latitude:standard_name = "latitude" ;
		latitude:long_name = "latitude" ;
		latitude:units = "degrees_north" ;
		latitude:axis = "Y" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:long_name = "time" ;
		time:bounds = "time_bnds" ;
		time:units = "hours since 1900-1-1 00:00:00" ;
		time:calendar = "standard" ;
		time:axis = "T" ;
	double time_bnds(time, bnds) ;
	short z(time, latitude, longitude) ;
		z:standard_name = "geopotential" ;
		z:long_name = "Geopotential" ;
		z:units = "m**2 s**-2" ;
		z:add_offset = 50852.7218502987 ;
		z:scale_factor = 0.259424402591061 ;
		z:_FillValue = -32767s ;
		z:missing_value = -32767s ;

**Comment by Peter-Gibson** [comment]
A follow-up question I had if you don't mind - Is it still valid to apply 'block_fast.R' on data that has not first been regridded to 2degree resolution (as done in z500_prepare.sh using cdo)? In other words, can I safely apply the script to raw model output at much higher (0.5deg resolution) - or are the blocking gradient calculations reliant on the 2degree grid?

**Comment by oloapinivad** [comment]
Hi Peter, 

thanks a lot: would it be possible for you to provide me a sample file to double check the netcdf.opener.time routine? 
Regarding your question, the code is not optimized for such approach. I checked the code and the TM90 index will not work for sure, conversely the 2D index "should" be fine. What is extremely important is that you start with a regular grid that is a factor of 2.5deg (i.e. 1.25, 0.5, etc.). Otherwise *all* the routines will work fine but they will consider different areas. 
Also, I am not sure plotting routines will sustain a different grid: however your point is a good suggestion, I will try to add this in the following commit.

Best,
Paolo

**Comment by Peter-Gibson** [comment]
Hi Paolo,

1. The file (0.4GB) produced after running 'z500_prepare.sh'  on my data is available here: https://www.dropbox.com/s/3kgqqjf7r928ief/Z500_ERA-INT_fullfile.nc?dl=0

2. Good to know about the grid requirements - I will bear that in mind and stick to using the default grid for the time being.

Thanks,
Peter

**Comment by oloapinivad** [comment]
Thanks for the sample,

Time_bnds as a variable is a bit weird. I guess that perhaps CDO is doing
something wrong?

I tried to solve it changing the way the code is accessing to the NetCDF
dimensions. Now is looking directly inside the variable attributes, that I
guess it is more correct.
I did a couple of testing and it "should" be solved: the changes have been
pushed on the master branch. This kind of changes are always very tricky
because they may impact other file formats.
Let me know if you can run the updated version or if you have any problem.

Best,
Paolo


2018-01-29 19:46 GMT+00:00 Peter Gibson <notifications@github.com>:

**Comment by Peter-Gibson** [comment]
Thanks Paolo,

I can confirm that the latest changes you have made has fixed the issue.

And you are right - the time_bnds variable was a bit odd. 
Further sensitivity testing revealed that when I do 'cdo daymean' on ERA-INT 6hrly data it created the time_bnds variable when using cdo v.1.7.2, but this doesn't happen with the latest version of cdo.

Thanks,
Peter

**Comment by oloapinivad** [comment]
@Peter-Gibson This is just to let you know that a further fix that improves the portability on different netcdf files has been pushed in a new commit on the master https://github.com/oloapinivad/MiLES/commit/a40b52720a41c1b3ed6002e4f7a7192b4e6adaf1.
